#!/bin/bash
# Quick Setup Guide for Production Deployment
# Run this after all files are created

echo "================================================"
echo "Koperasi PSM - Production Deployment Setup"
echo "================================================"
echo ""

echo "📋 Files Created:"
echo "✓ .env.production               - Production configuration"
echo "✓ .github/workflows/deploy.yml  - GitHub Actions CI/CD workflow"
echo "✓ deploy.sh                     - Deployment script (run on server)"
echo "✓ rollback.sh                   - Rollback script (if needed)"
echo "✓ health-check.sh               - Health check monitoring"
echo "✓ DEPLOYMENT.md                 - Detailed deployment guide"
echo "✓ GITHUB_SECRETS_SETUP.md       - Secrets configuration guide"
echo "✓ DEPLOYMENT_CHECKLIST.md       - Pre-deployment checklist"
echo ""

echo "⚠️  IMPORTANT: DO NOT COMMIT PRIVATE KEY!"
echo ""

echo "🔐 Next Steps:"
echo "1. Generate SSH key pair:"
echo "   ssh-keygen -t rsa -b 4096 -f deploy_key -N ''"
echo ""
echo "2. Add secrets to GitHub:"
echo "   Go to: Settings → Secrets and variables → Actions"
echo "   Add these secrets:"
echo "   • DEPLOY_KEY (content of deploy_key file)"
echo "   • SERVER_HOST"
echo "   • SERVER_USER"
echo "   • SERVER_PATH"
echo "   • DB_HOST"
echo "   • DB_PORT"
echo "   • DB_DATABASE"
echo "   • DB_USERNAME"
echo "   • DB_PASSWORD"
echo "   • SLACK_WEBHOOK (optional)"
echo ""

echo "3. Setup production server:"
echo "   - Create deployment user: sudo useradd -m -s /bin/bash deploy"
echo "   - Add SSH public key to authorized_keys"
echo "   - Create app directory: sudo mkdir -p /var/www/koperasi-psm"
echo "   - Install dependencies: PHP 8.2, MySQL, Node.js"
echo "   - Setup database and user"
echo "   - Configure Nginx with SSL"
echo ""

echo "4. Make scripts executable:"
echo "   chmod +x deploy.sh rollback.sh health-check.sh"
echo ""

echo "5. Configure .env.production:"
echo "   - Update APP_URL"
echo "   - Update Google OAuth credentials"
echo "   - Update database details"
echo "   - Update email credentials"
echo ""

echo "6. Commit and push:"
echo "   git add .github/ .env.production *.sh *.md"
echo "   git commit -m 'chore: add production deployment files'"
echo "   git push origin main"
echo ""

echo "📚 Documentation Files:"
echo "   • DEPLOYMENT.md              - Complete setup and troubleshooting"
echo "   • GITHUB_SECRETS_SETUP.md    - How to configure secrets safely"
echo "   • DEPLOYMENT_CHECKLIST.md    - Pre-deployment verification"
echo ""

echo "🚀 To Deploy:"
echo "   • Push to main branch"
echo "   • GitHub Actions will automatically run deploy.yml"
echo "   • Monitor in Actions tab"
echo ""

echo "⏮️  To Rollback (if needed):"
echo "   ssh deploy@SERVER_HOST"
echo "   cd /var/www/koperasi-psm"
echo "   bash rollback.sh"
echo ""

echo "✅ Security Checklist:"
echo "   ✓ Private key NOT in repository"
echo "   ✓ All secrets in GitHub Secrets only"
echo "   ✓ .env.production is configuration-only (no secrets)"
echo "   ✓ SSH key pair generated (4096-bit RSA)"
echo "   ✓ Strong database password (32+ characters)"
echo "   ✓ .gitignore properly configured"
echo ""

echo "================================================"
echo "Setup Complete! Ready for production deployment"
echo "================================================"
